apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  namespace: netperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
        - name: fortio
          image: fortio/fortio:latest
          args: ["server"]  # keep pod alive; we will exec fortio load inside
          ports:
            - containerPort: 8080
