kubeProxyReplacement: false

cni:
  chainingMode: aws-cni
  exclusive: false

enableIPv4Masquerade: false
routingMode: native

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

prometheus:
  enabled: true

operator:
  prometheus:
    enabled: true